* A set of Swing demos
** The purpose of this repository
   This repository contains an application with examples of Java Swing
   graphical user interface techniques. In the application, the
   different demos can be opened using checkboxes.
   
** Included demos
*** Table with changing data
    Demonstrates how to use class =AbstractTableModel= to link user
    data to table cells. The data can be changed via a menu item.
*** Table with editable boolean column
    Demonstrates how to have a checkbox column whose entries are
    linked to boolean variables.
*** Adding column elements to table
    Demonstrates how to add elements to the column of a table. Also
    shows how to show each data element (which in this case is a list)
    in a corresponding column of the table.
*** Multiple frames and switching panels
    Demonstrates two different ways to have multiple
    \ldquo{}views\rdquo in your application
    - multiple frames
    - one frame with switching panel (container).
*** Group layout
    Demonstrates the use of group layout, where you need to specify
    the positioning of the components both in vertical and horizontal
    direction.
*** Nested panels
    Demonstrates the construction of nested panels, that is,
    containers within containers.
*** Grid of panels
    Demonstrates the construction of a grid of panels, typical in
    applications with a calendar.
*** Complex event handlers
    Demonstrates complex event handling, where lambda expressions are
    no longer sufficient as event handlers. The methods illustrated
    are
    1. using an existing class to implement a listening interface:
       class =Main= as a =WindowFocusListener=
    2. using an anonymous class to implement a listening interface:
       =DocumentListener=.
*** Table cell rendering
    Demonstrates rendering (here, coloring) table cells with different
    colors depending on data shown.
*** Automatic gap resizing in group layout
    Demonstrates automatic horizontal alignment (\ldquo{}glue\rdquo)
    in a group layout.
** Installation in IDEA
   To install the application in IDEA, do the following:
   1. Clone the repository.
   2. Right click on class =Main=.
   3. Select =Run Main.main()=
   You are now able to make changes to the project and run it again.

** Alternative installation method
   1. Clone repository.
   2. Run =ant= default target (builds and runs the application).
   
** License
   Copyright (C) 2021 Jarmo Hurri

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
